### ISSUE TITLE
Probles  about  the  features  uesd to concatenate

### ISSUE THREAD

**Issue by Tclamber** [shijieS/SST#5]
Thanks for your great work . I don't make sense the process of  converting  reducted features  to  concatenated ones. For example ,red dot on the feature map to gain the red line feature. Specially，the last layer 3*3*20 gain Nm*20.Could you help me understand it ?

**Comment by shijieS** [comment]
Hi, @Tclamber . Thank you for your appreciation.  I am sorry for cannot understand number 3320, 20. I can explain concatenation. The feature vectors extracted at the same redpoint are concatenated together by *torch.cat*, see [code](https://github.com/shijieS/SST/blob/077801bf3a9e6ccbefaebb2742bf227837b9f443/layer/sst.py#L219). 

After concatenation, each red point corresponds to a feature vector of length 520.

**Comment by Tclamber** [comment]
Thank you for your reply . I  understand  now ! Besides,I miswritten it .(3*3*20)

**Comment by Tclamber** [comment]
Thank you for your rely! I understand now.Besides ,I miswritten it.(3plus 3 plus 20)
